
[voice_chat]
	#The distance to where the voice starts fading
	#Range: 1.0 ~ 1000000.0
	fade_distance = 16.0
	#The distance to where the voice can be heard
	#Range: 1.0 ~ 1000000.0
	distance = 32.0
	#The sample rate for the voice chat
	#Range: 10000 ~ 44100
	sample_rate = 16000
	#The port of the voice chat server
	#Range: 0 ~ 65535
	port = 24454
	#The maximum size in bytes in a voice packet
	#Set this to a lower value if your voice packets don't arrive
	#Range: 256 ~ 10000
	mtu_size = 900
	#The frequency in which keep alive packets are sent
	#Setting this to a higher value may result in timeouts
	#Range: > 1000
	keep_alive = 1000
	#The IP address to bind the voice chat server on
	#Leave empty to bind to an IP address chosen by the kernel
	bind_address = ""

